// Build-time only. Emits literal Python source: no filesystem assumptions at runtime.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { parse } from "yaml";
import { format } from "prettier";

const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = args.indexOf(name);
  return i < 0 ? fallback : resolve(args[i + 1]);
};
const here = dirname(fileURLToPath(import.meta.url));
// Explicit --infra after installation (scripts and infra occupy different roots).
const infra = flag("--infra", resolve(here, "../infra"));
const context = flag("--context", resolve(infra, "context"));
const f = parse(
  readFileSync(resolve(context, "account-fit-feature-contract.yaml"), "utf8"),
);
const c = parse(
  readFileSync(resolve(context, "account-fit-scoring.yaml"), "utf8"),
);
if (c.feature_contract_version !== f.version)
  throw new Error("Feature version mismatch");
if (
  args.includes("--approved") &&
  (c.approval.state !== "approved" ||
    f.approval.state !== "approved" ||
    c.synthetic ||
    f.synthetic ||
    !c.approval.reference ||
    !f.approval.reference)
) {
  throw new Error(
    "Live build requires both approved, non-synthetic contracts and approval references",
  );
}
// Reuse the scorer's contract validator at build time, including for drafts.
execFileSync(
  "python3",
  [
    "-c",
    "import sys,json;sys.path.insert(0,sys.argv[1]);from scorer import validate_contract;d=json.load(sys.stdin);validate_contract(d['features'],d['scoring'])",
    resolve(infra, "runtime"),
  ],
  {
    input: JSON.stringify({ features: f, scoring: c }),
    env: { ...process.env, PYTHONDONTWRITEBYTECODE: "1" },
  },
);
const source = readFileSync(resolve(infra, "runtime/scorer.py"), "utf8");
const preamble = `${source}\nFEATURES = json.loads(${JSON.stringify(JSON.stringify(f))})\nCONTRACT = json.loads(${JSON.stringify(JSON.stringify(c))})\n`;
const scripts = {
  normalizeScript: `${preamble}\nreturn normalize(nodes["start"], FEATURES, nodes["script"]["result"]["now"])`,
  scoringScript: `${preamble}\nrequest = nodes["start"]\nrequire(set(request) == {"snapshot", "contract_ref"}, "invalid action request")\nreturn score(request["snapshot"], request["contract_ref"], FEATURES, CONTRACT)`,
};
const markdown = await format(
  `---\ntitle: Account fit scoring contract\ndescription: Generated from the canonical feature and scoring contracts; do not edit.\n---\n\n# Account fit scoring\n\nApproval: ${c.approval.state}. Synthetic: ${c.synthetic}. Score version: ${c.version}. Feature version: ${f.version}.\n\nThis index measures structural fit, not readiness or a probability. Python computes it; the agent explains applied rules and evidence.\n\n## Feature contract\n\n\`\`\`json\n${JSON.stringify(f, null, 2)}\n\`\`\`\n\n## Outcome and scoring contract\n\n\`\`\`json\n${JSON.stringify(c, null, 2)}\n\`\`\`\n`,
  { parser: "markdown" },
);
const code = await format(
  `// Generated by scripts/build.mjs. Do not edit.\n${Object.entries(scripts)
    .map(([k, v]) => `export const ${k} = ${JSON.stringify(v)};`)
    .join(
      "\n",
    )}\nexport const scoringVersion = ${JSON.stringify(c.version)};\nexport const featureVersion = ${JSON.stringify(f.version)};\nexport const tierNames = ${JSON.stringify(c.thresholds.map((t) => t.tier))} as const;\nexport const scoringContext = ${JSON.stringify(markdown)};\nexport const sourceHash = ${JSON.stringify(createHash("sha256").update(source).digest("hex"))};\n`,
  { parser: "typescript" },
);
const liveCapable =
  c.approval.state === "approved" &&
  f.approval.state === "approved" &&
  !c.synthetic &&
  !f.synthetic;
// This guard is mandatory for every live-capable bundle, even without --approved.
if (liveCapable) {
  if (!/^[a-zA-Z0-9_-]+$/.test(c.version))
    throw new Error("Unsafe version path");
  for (const [kind, value] of [
    ["features", f],
    ["outcome", c.outcome],
  ]) {
    if (!/^[a-zA-Z0-9_-]+$/.test(value.version))
      throw new Error("Unsafe version path");
    const directory = resolve(context, "account-fit-versions", kind);
    const target = resolve(directory, `${value.version}.json`);
    const body = JSON.stringify(value, null, 2) + "\n";
    if (existsSync(target) && readFileSync(target, "utf8") !== body)
      throw new Error(`Approved ${kind} version is immutable`);
    if (!existsSync(target)) {
      if (args.includes("--check"))
        throw new Error(`Approved ${kind} archive missing`);
      mkdirSync(directory, { recursive: true });
      writeFileSync(target, body);
    }
  }
  const archive = resolve(context, "account-fit-versions", c.version);
  const body = JSON.stringify({ features: f, scoring: c }, null, 2) + "\n";
  const target = resolve(archive, "contracts.json");
  if (existsSync(target) && readFileSync(target, "utf8") !== body)
    throw new Error("Approved versions are immutable; increment version");
  if (!existsSync(target)) {
    if (args.includes("--check")) throw new Error("Approved archive missing");
    mkdirSync(archive, { recursive: true });
    writeFileSync(target, body);
  }
}
for (const [path, content] of [
  [resolve(infra, "runtime/generated.ts"), code],
  [resolve(context, "account-fit-scoring.md"), markdown],
]) {
  if (args.includes("--check")) {
    if (readFileSync(path, "utf8") !== content)
      throw new Error(`Generated asset drift: ${path}`);
  } else {
    writeFileSync(path, content);
  }
}
console.log(
  args.includes("--check")
    ? "ok: generated assets match contracts and Python"
    : "Generated Python bundle and scoring context",
);
