// Build-time only. Emits literal Python source: no filesystem assumptions at runtime.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { parse } from "yaml";
import { format } from "prettier";

const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = args.indexOf(name);
  return i < 0 ? fallback : resolve(args[i + 1]);
};
const here = dirname(fileURLToPath(import.meta.url));
// Explicit --infra after installation (scripts and infra occupy different roots).
const infra = flag("--infra", resolve(here, "../infra"));
const context = flag("--context", resolve(infra, "context"));
const f = parse(
  readFileSync(resolve(context, "account-fit-feature-contract.yaml"), "utf8"),
);
const c = parse(
  readFileSync(resolve(context, "account-fit-scoring.yaml"), "utf8"),
);
if (c.feature_contract_version !== f.version)
  throw new Error("Feature version mismatch");
const approved =
  c.approval.state === "approved" &&
  f.approval.state === "approved" &&
  Boolean(c.approval.reference) &&
  Boolean(f.approval.reference);
const demoIds = c.demo_account_ids ?? [];
const uncalibrated = f.features
  .filter((x) => x.type === "number" && !x.calibrated_range)
  .map((x) => x.name);
if (args.includes("--approved") && args.includes("--demo"))
  throw new Error("Choose --approved (live) or --demo (fixtures), not both");
if (
  args.includes("--approved") &&
  (!approved || c.synthetic || f.synthetic || demoIds.length > 0)
) {
  throw new Error(
    "Live build requires both approved, non-synthetic contracts and approval references",
  );
}
if (
  args.includes("--demo") &&
  (!approved || !c.synthetic || !f.synthetic || demoIds.length === 0)
) {
  throw new Error(
    "Demo build requires approved synthetic contracts with demo_account_ids",
  );
}
// Live and demo bundles are both deployable, with or without a flag: both need
// calibrated ranges and both archive immutably.
const deployable =
  approved && ((!c.synthetic && !f.synthetic) || demoIds.length > 0);
if (deployable && uncalibrated.length > 0) {
  throw new Error(
    `Numeric features need calibrated_range: ${uncalibrated.join(", ")}`,
  );
}
// Reuse the scorer's contract validator at build time, including for drafts.
execFileSync(
  "python3",
  [
    "-c",
    "import sys,json;sys.path.insert(0,sys.argv[1]);from scorer import validate_contract;d=json.load(sys.stdin);validate_contract(d['features'],d['scoring'])",
    resolve(infra, "runtime"),
  ],
  {
    input: JSON.stringify({ features: f, scoring: c }),
    env: { ...process.env, PYTHONDONTWRITEBYTECODE: "1" },
  },
);
const source = readFileSync(resolve(infra, "runtime/scorer.py"), "utf8");
const preamble = `${source}\nFEATURES = json.loads(${JSON.stringify(JSON.stringify(f))})\nCONTRACT = json.loads(${JSON.stringify(JSON.stringify(c))})\n`;
const scripts = {
  normalizeScript: `${preamble}\nreturn normalize(nodes["start"], FEATURES, nodes["script"]["result"]["now"])`,
  scoringScript: `${preamble}\nrequest = nodes["start"]\nrequire(set(request) == {"snapshot", "contract_ref"}, "invalid action request")\nreturn score(request["snapshot"], request["contract_ref"], FEATURES, CONTRACT)`,
};
const markdown = await format(
  `---\ntitle: Account fit scoring contract\ndescription: Generated from the canonical feature and scoring contracts; do not edit.\n---\n\n# Account fit scoring\n\nApproval: ${c.approval.state}. Synthetic: ${c.synthetic}. Score version: ${c.version}. Feature version: ${f.version}.\n\nThis index measures structural fit, not readiness or a probability. Python computes it; the agent explains applied rules and evidence.\n\n## Feature contract\n\n\`\`\`json\n${JSON.stringify(f, null, 2)}\n\`\`\`\n\n## Outcome and scoring contract\n\n\`\`\`json\n${JSON.stringify(c, null, 2)}\n\`\`\`\n`,
  { parser: "markdown" },
);
const code = await format(
  `// Generated by scripts/build.mjs. Do not edit.\n${Object.entries(scripts)
    .map(([k, v]) => `export const ${k} = ${JSON.stringify(v)};`)
    .join(
      "\n",
    )}\nexport const scoringVersion = ${JSON.stringify(c.version)};\nexport const demoAccountIds: readonly string[] = ${JSON.stringify(demoIds)};\nexport const featureVersion = ${JSON.stringify(f.version)};\nexport const tierNames = ${JSON.stringify(c.thresholds.map((t) => t.tier))} as const;\nexport const scoringContext = ${JSON.stringify(markdown)};\nexport const sourceHash = ${JSON.stringify(createHash("sha256").update(source).digest("hex"))};\n`,
  { parser: "typescript" },
);
// This guard is mandatory for every deployable bundle, even without a flag.
if (deployable) {
  if (!/^[a-zA-Z0-9_-]+$/.test(c.version))
    throw new Error("Unsafe version path");
  const archives = [];
  for (const [kind, value] of [
    ["features", f],
    ["outcome", c.outcome],
  ]) {
    if (!/^[a-zA-Z0-9_-]+$/.test(value.version))
      throw new Error("Unsafe version path");
    const directory = resolve(context, "account-fit-versions", kind);
    const target = resolve(directory, `${value.version}.json`);
    const body = JSON.stringify(value, null, 2) + "\n";
    archives.push({ kind, directory, target, body });
  }
  const scoreDirectory = resolve(context, "account-fit-versions", c.version);
  archives.push({
    kind: "score",
    directory: scoreDirectory,
    target: resolve(scoreDirectory, "contracts.json"),
    body: JSON.stringify({ features: f, scoring: c }, null, 2) + "\n",
  });
  // Validate the complete archive set before writing any member. A failed build
  // must not claim a version with partial artifacts.
  for (const archive of archives) {
    if (
      existsSync(archive.target) &&
      readFileSync(archive.target, "utf8") !== archive.body
    ) {
      throw new Error(
        archive.kind === "score"
          ? "Approved versions are immutable; increment version"
          : `Approved ${archive.kind} version is immutable`,
      );
    }
    if (!existsSync(archive.target) && args.includes("--check"))
      throw new Error(`Approved ${archive.kind} archive missing`);
  }
  for (const archive of archives) {
    if (!existsSync(archive.target)) {
      mkdirSync(archive.directory, { recursive: true });
      writeFileSync(archive.target, archive.body);
    }
  }
}
for (const [path, content] of [
  [resolve(infra, "runtime/generated.ts"), code],
  [resolve(context, "account-fit-scoring.md"), markdown],
]) {
  if (args.includes("--check")) {
    if (readFileSync(path, "utf8") !== content)
      throw new Error(`Generated asset drift: ${path}`);
  } else {
    writeFileSync(path, content);
  }
}
console.log(
  args.includes("--check")
    ? "ok: generated assets match contracts and Python"
    : "Generated Python bundle and scoring context",
);
