/**
 * Generates llms.txt from the actual skill tree.
 *
 *   node scripts/generate-llms-txt.ts          # write llms.txt
 *   node scripts/generate-llms-txt.ts --check  # CI: fail if stale
 *
 * llms.txt is how an LLM-facing crawler reads a repository without guessing at
 * its structure: one file, at a predictable path, listing what is here and what
 * each thing does. For a repo whose entire purpose is being *found*, a stale or
 * missing one is a self-inflicted wound — so it is generated from the skills
 * themselves and checked in CI rather than maintained by hand.
 *
 * Requires Node >= 22.18 (run as .ts via native type-stripping).
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outPath = join(repoRoot, "llms.txt");
const repoUrl = "https://github.com/getcargohq/gtm-skills";
const packUrl = "https://github.com/getcargohq/cargo-skills";

interface Skill {
  name: string;
  description: string;
  /** First sentence of the description — the job, without the trigger list. */
  job: string;
}

function loadSkills(): Skill[] {
  const skills: Skill[] = [];
  for (const entry of readdirSync(repoRoot).sort()) {
    const skillMd = join(repoRoot, entry, "SKILL.md");
    if (!statSync(join(repoRoot, entry), { throwIfNoEntry: false })?.isDirectory()) continue;
    if (!existsSync(skillMd)) continue;

    const frontmatter = /^---\n([\s\S]*?)\n---/.exec(readFileSync(skillMd, "utf8"))?.[1];
    if (!frontmatter) throw new Error(`${entry}/SKILL.md has no frontmatter`);

    let name = "";
    let description = "";
    for (const line of frontmatter.split("\n")) {
      const field = /^(name|description):\s*(.+)$/.exec(line);
      if (!field) continue;
      let value = field[2].trim();
      if (value.startsWith('"') && value.endsWith('"')) value = JSON.parse(value);
      if (field[1] === "name") name = value;
      else description = value;
    }
    if (!name || !description) throw new Error(`${entry}/SKILL.md is missing name or description`);

    skills.push({ name, description, job: description.split(/\.\s+Triggers:/)[0] + "." });
  }
  return skills;
}

function render(skills: Skill[]): string {
  const lines = skills
    .map((s) => `- [${s.name}](${repoUrl}/blob/main/${s.name}/SKILL.md): ${s.description}`)
    .join("\n");

  const jobs = skills.map((s) => `- **${s.name}** — ${s.job}`).join("\n");

  return `# Cargo GTM Skills

> ${skills.length} standalone agent skills for go-to-market work — finding B2B leads, building target account lists, resolving LinkedIn URLs, finding and verifying work emails, enriching companies and people, mapping buying committees, and tracking job changes, funding rounds, and tech-stack signals. Each does one job and installs on its own. Some carry a worked CDK example instead of a command: the same job as a deployed pipeline that keeps running, which your agent adapts into your project. Powered by [Cargo](https://getcargo.ai).

## Install

All of them:

\`\`\`bash
npx skills add getcargohq/gtm-skills --all
\`\`\`

Or exactly one:

\`\`\`bash
npx skills add getcargohq/gtm-skills/<skill-name>
\`\`\`

Then sign in — this creates the account and workspace on first use, with no browser and no separate sign-up step:

\`\`\`bash
npm install -g @cargo-ai/cli
cargo-ai login --email you@company.com          # sends a code, then exits
cargo-ai login --email you@company.com --code 123456
\`\`\`

A new account starts with **100 free credits and needs no card** — roughly 5,000 leads sourced, or 1,000 profile-plus-verified-email enrichments. Every skill here runs end to end inside that balance, so there is no purchase gate between installing one and getting a real result.

## Skills

${lines}

## What each one does

${jobs}

## The full pack

These are single-job slices. The complete [Cargo skills pack](${packUrl}) is 17 skills covering the whole CLI — workflow orchestration, storage and segmentation, agents and RAG, workspace-as-code, diagnostics, and billing — with recipes, per-provider playbooks, and cost discipline built in:

\`\`\`bash
npx skills add getcargohq/cargo-skills
\`\`\`

Install the pack *or* these, not both: each skill here defers to \`cargo-gtm\` when the pack is present.

## Documentation

- [Cargo](https://getcargo.ai)
- [Cargo API docs](https://docs.getcargo.ai/api-reference/introduction)
- [Full skills pack](${packUrl})
- [This repository](${repoUrl})

<!-- Generated by scripts/generate-llms-txt.ts — do not edit by hand. -->
`;
}

const generated = render(loadSkills());

if (process.argv.includes("--check")) {
  const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (current !== generated) {
    console.error("llms.txt is stale. Regenerate with: node scripts/generate-llms-txt.ts");
    process.exit(1);
  }
  console.log("llms.txt is up to date.");
} else {
  writeFileSync(outPath, generated);
  console.log(`Wrote ${outPath}`);
}
